Repository eastheat10/dont-ask-to-me, pull requests merged in 2023-05, with the labels that each got.

#8 style : style-layout
  css/index.css
  css/style.css
  html/index.html
Labels: feature

#12 Feature/toast
  html/index.html
  html/login.html
Labels: feature

#14 Feature/post write
  html/index.html
  src/app.js
  src/firebase/PostRepository.js
  src/firebase/commentRepository.js
  src/firebase/index.js
  src/post/index.js
Labels: feature

#15 Feature/post paging
  html/index.html
  src/app.js
  src/firebase/PostRepository.js
  src/post/index.js
Labels: feature

#16 Feature/post more
  html/index.html
  html/login.html
  src/app.js
  src/firebase/PostRepository.js
  src/firebase/commentRepository.js
  src/firebase/index.js
  src/post/index.js
Labels: feature

#17 Feature/read
  css/index.css
  html/index.html
  src/app.js
  src/firebase/PostRepository.js
  src/post/index.js
Labels: feature

#19 refactor : toastui
  html/index.html
  html/login.html
  src/toastui.js
Labels: refactor

#21 style: css 적용 #20
  css/index.css
  html/index.html
  src/app.js
Labels: style

#22 feat : 게시글 추가 및 삭제
  src/app.js
  src/firebase/PostRepository.js
  src/firebase/commentRepository.js
  src/post/index.js
  src/toastui.js
Labels: feature

#23 카카오 로그인 및 게시글 crud
  css/index.css
  html/index.html
  html/login.html
  src/app.js
  src/firebase/PostRepository.js
  src/firebase/commentRepository.js
  src/post/index.js
  src/toastui.js
Labels: feature

#25 Feature/post comment
  css/index.css
  html/index.html
  src/app.js
  src/firebase/PostRepository.js
  src/post/index.js
Labels: feature

#26 refactor
  src/app.js
Labels: refactor
